language: python
python:
  - 3.9
  - 3.8
  - 3.7

before_install:
  - pip install poetry

install: poetry install

script: tox

deploy:
  provider: script
  script: poetry publish -r rocketLauncher
  distributions: sdist bdist_wheel
  user: drearondov
  password:
    secure: 16Rocket&Launcher22
  on:
    tags: true
    repo: drearondov/rocket_launcher
    python: 3.9
